version: '3.8'

services:

  docbill:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docbill
      POSTGRES_PASSWORD: docbill
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
     
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    restart: always
    ports:
      - 8081:8081
      
volumes:
  pgdata:
